# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
echo I am provisioning...
date > /etc/vagrant_provisioned_at
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "private_network", ip: "192.168.88.88"
  config.vm.provision "shell", inline: $script
  config.vm.synced_folder "../", "/home/vagrant/quehacemos", create:true,
    :mount_options => ['dmode=775', 'fmode=777']
  config.vm.provision :shell, path: "Vagrant-setup/bootstrap.sh"
end
