/* 0001-system.sql */

insert into countries (	id, prnt, iso, name, ccode, cname, pcoderx, langs) values
 ('AD', NULL, 'AD', 'Andorra', 'EUR', 'Euro', '^(?:AD)*(\d{3})$', 'ca'),
 ('AE', NULL, 'AE', 'United Arab Emirates', 'AED', 'Dirham', null, 'ar-AE,fa,en,hi,ur' ),
 ('AF', NULL, 'AF', 'Afghanistan', 'AFN', 'Afghani', null, 'fa-AF,ps,uz-AF,tk' ),
 ('AG', NULL, 'AG', 'Antigua and Barbuda', 'XCD', 'Dollar', null, 'en-AG' ),
 ('AI', NULL, 'AI', 'Anguilla', 'XCD', 'Dollar', null, 'en-AI' ),
 ('AM', NULL, 'AM', 'Armenia', 'AMD', 'Dram', '^(\d{6})$', 'hy' ),
 ('AO', NULL, 'AO', 'Angola', 'AOA', 'Kwanza', null, 'pt-AO' ),
 ('AQ', NULL, 'AQ', 'Antarctica', null, null, null, null ),
 ('AR', NULL, 'AR', 'Argentina', 'ARS', 'Peso', '^[A-Z]?\d{4}[A-Z]{0,3}$', 'es-AR,en,it,de,fr,gn' ),
 ('AS', NULL, 'AS', 'American Samoa', 'USD', 'Dollar', '96799', 'en-AS,sm,to' ),
 ('AT', NULL, 'AT', 'Austria', 'EUR', 'Euro', '^(\d{4})$', 'de-AT,hr,hu,sl' ),
 ('AU', NULL, 'AU', 'Australia', 'AUD', 'Dollar', '^(\d{4})$', 'en-AU' ),
 ('AW', NULL, 'AW', 'Aruba', 'AWG', 'Guilder', null, 'nl-AW,es,en' ),
 ('AX', NULL, 'AX', 'Aland Islands', 'EUR', 'Euro', '^(?:FI)*(\d{5})$', 'sv-AX' ),
 ('AZ', NULL, 'AZ', 'Azerbaijan', 'AZN', 'Manat', '^(?:AZ)*(\d{4})$', 'az,ru,hy' ),
 ('BA', NULL, 'BA', 'Bosnia and Herzegovina', 'BAM', 'Marka', '^(\d{5})$', 'bs,hr-BA,sr-BA' ),
 ('BB', NULL, 'BB', 'Barbados', 'BBD', 'Dollar', '^(?:BB)*(\d{5})$', 'en-BB' ),
 ('BD', NULL, 'BD', 'Bangladesh', 'BDT', 'Taka', '^(\d{4})$', 'bn-BD,en' ),
 ('BE', NULL, 'BE', 'Belgium', 'EUR', 'Euro', '^(\d{4})$', 'nl-BE,fr-BE,de-BE' ),
 ('BF', NULL, 'BF', 'Burkina Faso', 'XOF', 'Franc', null, 'fr-BF' ),
 ('BG', NULL, 'BG', 'Bulgaria', 'BGN', 'Lev', '^(\d{4})$', 'bg,tr-BG,rom' ),
 ('BH', NULL, 'BH', 'Bahrain', 'BHD', 'Dinar', '^(\d{3}\d?)$', 'ar-BH,en,fa,ur' ),
 ('BI', NULL, 'BI', 'Burundi', 'BIF', 'Franc', null, 'fr-BI,rn' ),
 ('BJ', NULL, 'BJ', 'Benin', 'XOF', 'Franc', null, 'fr-BJ' ),
 ('BL', NULL, 'BL', 'Saint Barthelemy', 'EUR', 'Euro', null, 'fr' ),
 ('BM', NULL, 'BM', 'Bermuda', 'BMD', 'Dollar', '^([A-Z]{2}\d{2})$', 'en-BM,pt' ),
 ('BN', NULL, 'BN', 'Brunei', 'BND', 'Dollar', '^([A-Z]{2}\d{4})$', 'ms-BN,en-BN' ),
 ('BO', NULL, 'BO', 'Bolivia', 'BOB', 'Boliviano', null, 'es-BO,qu,ay' ),
 ('BQ', NULL, 'BQ', 'Bonaire, Saint Eustatius and Saba ', 'USD', 'Dollar', null, 'nl,pap,en' ),
 ('BR', NULL, 'BR', 'Brazil', 'BRL', 'Real', '^\d{5}-\d{3}$', 'pt-BR,es,en,fr' ),
 ('BS', NULL, 'BS', 'Bahamas', 'BSD', 'Dollar', null, 'en-BS' ),
 ('BT', NULL, 'BT', 'Bhutan', 'BTN', 'Ngultrum', null, 'dz' ),
 ('BV', NULL, 'BV', 'Bouvet Island', 'NOK', 'Krone', null, null ),
 ('BW', NULL, 'BW', 'Botswana', 'BWP', 'Pula', null, 'en-BW,tn-BW' ),
 ('BY', NULL, 'BY', 'Belarus', 'BYR', 'Ruble', '^(\d{6})$', 'be,ru' ),
 ('BZ', NULL, 'BZ', 'Belize', 'BZD', 'Dollar', null, 'en-BZ,es' ),
 ('CA', NULL, 'CA', 'Canada', 'CAD', 'Dollar', '^([ABCEGHJKLMNPRSTVXY]\d[ABCEGHJKLMNPRSTVWXYZ]) ?(\d[ABCEGHJKLMNPRSTVWXYZ]\d)$ ', 'en-CA,fr-CA,iu' ),
 ('CC', NULL, 'CC', 'Cocos Islands', 'AUD', 'Dollar', null, 'ms-CC,en' ),
 ('CD', NULL, 'CD', 'Democratic Republic of the Congo', 'CDF', 'Franc', null, 'fr-CD,ln,kg' ),
 ('CF', NULL, 'CF', 'Central African Republic', 'XAF', 'Franc', null, 'fr-CF,sg,ln,kg' ),
 ('CG', NULL, 'CG', 'Republic of the Congo', 'XAF', 'Franc', null, 'fr-CG,kg,ln-CG' ),
 ('CH', NULL, 'CH', 'Switzerland', 'CHF', 'Franc', '^(\d{4})$', 'de-CH,fr-CH,it-CH,rm' ),
 ('CI', NULL, 'CI', 'Ivory Coast', 'XOF', 'Franc', null, 'fr-CI' ),
 ('CK', NULL, 'CK', 'Cook Islands', 'NZD', 'Dollar', null, 'en-CK,mi' ),
 ('CL', NULL, 'CL', 'Chile', 'CLP', 'Peso', '^(\d{7})$', 'es-CL' ),
 ('CM', NULL, 'CM', 'Cameroon', 'XAF', 'Franc', null, 'en-CM,fr-CM' ),
 ('CN', NULL, 'CN', 'China', 'CNY', 'Yuan Renminbi', '^(\d{6})$', 'zh-CN,yue,wuu,dta,ug,za' ),
 ('CO', NULL, 'CO', 'Colombia', 'COP', 'Peso', null, 'es-CO' ),
 ('CR', NULL, 'CR', 'Costa Rica', 'CRC', 'Colon', '^(\d{5})$', 'es-CR,en' ),
 ('CU', NULL, 'CU', 'Cuba', 'CUP', 'Peso', '^(?:CP)*(\d{5})$', 'es-CU' ),
 ('CV', NULL, 'CV', 'Cape Verde', 'CVE', 'Escudo', '^(\d{4})$', 'pt-CV' ),
 ('CW', NULL, 'CW', 'Curacao', 'ANG', 'Guilder', null, 'nl,pap' ),
 ('CX', NULL, 'CX', 'Christmas Island', 'AUD', 'Dollar', '^(\d{4})$', 'en,zh,ms-CC' ),
 ('CY', NULL, 'CY', 'Cyprus', 'EUR', 'Euro', '^(\d{4})$', 'el-CY,tr-CY,en' ),
 ('CZ', NULL, 'CZ', 'Czechia', 'CZK', 'Koruna', '^\d{3}\s?\d{2}$', 'cs,sk' ),
 ('DE', NULL, 'DE', 'Germany', 'EUR', 'Euro', '^(\d{5})$', 'de' ),
 ('DJ', NULL, 'DJ', 'Djibouti', 'DJF', 'Franc', null, 'fr-DJ,ar,so-DJ,aa' ),
 ('DK', NULL, 'DK', 'Denmark', 'DKK', 'Krone', '^(\d{4})$', 'da-DK,en,fo,de-DK' ),
 ('DM', NULL, 'DM', 'Dominica', 'XCD', 'Dollar', null, 'en-DM' ),
 ('DO', NULL, 'DO', 'Dominican Republic', 'DOP', 'Peso', '^(\d{5})$', 'es-DO' ),
 ('DZ', NULL, 'DZ', 'Algeria', 'DZD', 'Dinar', '^(\d{5})$', 'ar-DZ' ),
 ('EC', NULL, 'EC', 'Ecuador', 'USD', 'Dollar', '^([a-zA-Z]\d{4}[a-zA-Z])$', 'es-EC' ),
 ('EE', NULL, 'EE', 'Estonia', 'EUR', 'Euro', '^(\d{5})$', 'et,ru' ),
 ('EG', NULL, 'EG', 'Egypt', 'EGP', 'Pound', '^(\d{5})$', 'ar-EG,en,fr' ),
 ('EH', NULL, 'EH', 'Western Sahara', 'MAD', 'Dirham', null, 'ar,mey' ),
 ('ER', NULL, 'ER', 'Eritrea', 'ERN', 'Nakfa', null, 'aa-ER,ar,tig,kun,ti-ER' ),
 ('ES', NULL, 'ES', 'Spain', 'EUR', 'Euro', '^(\d{5})$', 'es-ES,ca,gl,eu,oc' ),
 ('ET', NULL, 'ET', 'Ethiopia', 'ETB', 'Birr', '^(\d{4})$', 'am,en-ET,om-ET,ti-ET,so-ET,sid' ),
 ('FI', NULL, 'FI', 'Finland', 'EUR', 'Euro', '^(?:FI)*(\d{5})$', 'fi-FI,sv-FI,smn' ),
 ('FJ', NULL, 'FJ', 'Fiji', 'FJD', 'Dollar', null, 'en-FJ,fj' ),
 ('FK', NULL, 'FK', 'Falkland Islands', 'FKP', 'Pound', null, 'en-FK' ),
 ('FM', NULL, 'FM', 'Micronesia', 'USD', 'Dollar', '^(\d{5})$', 'en-FM,chk,pon,yap,kos,uli,woe,nkr,kpg' ),
 ('FO', NULL, 'FO', 'Faroe Islands', 'DKK', 'Krone', '^(?:FO)*(\d{3})$', 'fo,da-FO' ),
 ('FR', NULL, 'FR', 'France', 'EUR', 'Euro', '^(\d{5})$', 'fr-FR,frp,br,co,ca,eu,oc' ),
 ('GA', NULL, 'GA', 'Gabon', 'XAF', 'Franc', null, 'fr-GA' ),
 ('GB', NULL, 'GB', 'United Kingdom', 'GBP', 'Pound', '^((?:(?:[A-PR-UWYZ][A-HK-Y]\d[ABEHMNPRV-Y0-9]|[A-PR-UWYZ]\d[A-HJKPS-UW0-9])\s\d[ABD-HJLNP-UW-Z]{2})|GIR\s?0AA)$', 'en-GB,cy-GB,gd' ),
 ('GD', NULL, 'GD', 'Grenada', 'XCD', 'Dollar', null, 'en-GD' ),
 ('GE', NULL, 'GE', 'Georgia', 'GEL', 'Lari', '^(\d{4})$', 'ka,ru,hy,az' ),
 ('GF', NULL, 'GF', 'French Guiana', 'EUR', 'Euro', '^((97|98)3\d{2})$', 'fr-GF' ),
 ('GG', NULL, 'GG', 'Guernsey', 'GBP', 'Pound', '^((?:(?:[A-PR-UWYZ][A-HK-Y]\d[ABEHMNPRV-Y0-9]|[A-PR-UWYZ]\d[A-HJKPS-UW0-9])\s\d[ABD-HJLNP-UW-Z]{2})|GIR\s?0AA)$', 'en,fr' ),
 ('GH', NULL, 'GH', 'Ghana', 'GHS', 'Cedi', null, 'en-GH,ak,ee,tw' ),
 ('GI', NULL, 'GI', 'Gibraltar', 'GIP', 'Pound', null, 'en-GI,es,it,pt' ),
 ('GL', NULL, 'GL', 'Greenland', 'DKK', 'Krone', '^(\d{4})$', 'kl,da-GL,en' ),
 ('GM', NULL, 'GM', 'Gambia', 'GMD', 'Dalasi', null, 'en-GM,mnk,wof,wo,ff' ),
 ('GN', NULL, 'GN', 'Guinea', 'GNF', 'Franc', null, 'fr-GN' ),
 ('GP', NULL, 'GP', 'Guadeloupe', 'EUR', 'Euro', '^((97|98)\d{3})$', 'fr-GP' ),
 ('GQ', NULL, 'GQ', 'Equatorial Guinea', 'XAF', 'Franc', null, 'es-GQ,fr' ),
 ('GR', NULL, 'GR', 'Greece', 'EUR', 'Euro', '^(\d{5})$', 'el-GR,en,fr' ),
 ('GS', NULL, 'GS', 'South Georgia and the South Sandwich Islands', 'GBP', 'Pound', null, 'en' ),
 ('GT', NULL, 'GT', 'Guatemala', 'GTQ', 'Quetzal', '^(\d{5})$', 'es-GT' ),
 ('GU', NULL, 'GU', 'Guam', 'USD', 'Dollar', '^(969\d{2})$', 'en-GU,ch-GU' ),
 ('GW', NULL, 'GW', 'Guinea-Bissau', 'XOF', 'Franc', '^(\d{4})$', 'pt-GW,pov' ),
 ('GY', NULL, 'GY', 'Guyana', 'GYD', 'Dollar', null, 'en-GY' ),
 ('HK', NULL, 'HK', 'Hong Kong', 'HKD', 'Dollar', null, 'zh-HK,yue,zh,en' ),
 ('HM', NULL, 'HM', 'Heard Island and McDonald Islands', 'AUD', 'Dollar', null, null ),
 ('HN', NULL, 'HN', 'Honduras', 'HNL', 'Lempira', '^([A-Z]{2}\d{4})$', 'es-HN' ),
 ('HR', NULL, 'HR', 'Croatia', 'HRK', 'Kuna', '^(?:HR)*(\d{5})$', 'hr-HR,sr' ),
 ('HT', NULL, 'HT', 'Haiti', 'HTG', 'Gourde', '^(?:HT)*(\d{4})$', 'ht,fr-HT' ),
 ('HU', NULL, 'HU', 'Hungary', 'HUF', 'Forint', '^(\d{4})$', 'hu-HU' ),
 ('ID', NULL, 'ID', 'Indonesia', 'IDR', 'Rupiah', '^(\d{5})$', 'id,en,nl,jv' ),
 ('IE', NULL, 'IE', 'Ireland', 'EUR', 'Euro', '^[A-Z]\d{2}$|^[A-Z]{3}[A-Z]{4}$', 'en-IE,ga-IE' ),
 ('IL', NULL, 'IL', 'Israel', 'ILS', 'Shekel', '^(\d{5})$', 'he,ar-IL,en-IL,' ),
 ('IM', NULL, 'IM', 'Isle of Man', 'GBP', 'Pound', '^((?:(?:[A-PR-UWYZ][A-HK-Y]\d[ABEHMNPRV-Y0-9]|[A-PR-UWYZ]\d[A-HJKPS-UW0-9])\s\d[ABD-HJLNP-UW-Z]{2})|GIR\s?0AA)$', 'en,gv' ),
 ('IN', NULL, 'IN', 'India', 'INR', 'Rupee', '^(\d{6})$', 'en-IN,hi,bn,te,mr,ta,ur,gu,kn,ml,or,pa,as,bh,sat,ks,ne,sd,kok,doi,mni,sit,sa,fr,lus,inc' ),
 ('IO', NULL, 'IO', 'British Indian Ocean Territory', 'USD', 'Dollar', null, 'en-IO' ),
 ('IQ', NULL, 'IQ', 'Iraq', 'IQD', 'Dinar', '^(\d{5})$', 'ar-IQ,ku,hy' ),
 ('IR', NULL, 'IR', 'Iran', 'IRR', 'Rial', '^(\d{10})$', 'fa-IR,ku' ),
 ('IS', NULL, 'IS', 'Iceland', 'ISK', 'Krona', '^(\d{3})$', 'is,en,de,da,sv,no' ),
 ('IT', NULL, 'IT', 'Italy', 'EUR', 'Euro', '^(\d{5})$', 'it-IT,de-IT,fr-IT,sc,ca,co,sl' ),
 ('JE', NULL, 'JE', 'Jersey', 'GBP', 'Pound', '^((?:(?:[A-PR-UWYZ][A-HK-Y]\d[ABEHMNPRV-Y0-9]|[A-PR-UWYZ]\d[A-HJKPS-UW0-9])\s\d[ABD-HJLNP-UW-Z]{2})|GIR\s?0AA)$', 'en,pt' ),
 ('JM', NULL, 'JM', 'Jamaica', 'JMD', 'Dollar', null, 'en-JM' ),
 ('JO', NULL, 'JO', 'Jordan', 'JOD', 'Dinar', '^(\d{5})$', 'ar-JO,en' ),
 ('JP', NULL, 'JP', 'Japan', 'JPY', 'Yen', '^\d{3}-\d{4}$', 'ja' ),
 ('KE', NULL, 'KE', 'Kenya', 'KES', 'Shilling', '^(\d{5})$', 'en-KE,sw-KE' ),
 ('KG', NULL, 'KG', 'Kyrgyzstan', 'KGS', 'Som', '^(\d{6})$', 'ky,uz,ru' ),
 ('KH', NULL, 'KH', 'Cambodia', 'KHR', 'Riels', '^(\d{5})$', 'km,fr,en' ),
 ('KI', NULL, 'KI', 'Kiribati', 'AUD', 'Dollar', null, 'en-KI,gil' ),
 ('KM', NULL, 'KM', 'Comoros', 'KMF', 'Franc', null, 'ar,fr-KM' ),
 ('KN', NULL, 'KN', 'Saint Kitts and Nevis', 'XCD', 'Dollar', null, 'en-KN' ),
 ('KP', NULL, 'KP', 'North Korea', 'KPW', 'Won', '^(\d{6})$', 'ko-KP' ),
 ('KR', NULL, 'KR', 'South Korea', 'KRW', 'Won', '^(?:SEOUL)*(\d{6})$', 'ko-KR,en' ),
 ('XK', NULL, 'XK', 'Kosovo', 'EUR', 'Euro', null, 'sq,sr' ),
 ('KW', NULL, 'KW', 'Kuwait', 'KWD', 'Dinar', '^(\d{5})$', 'ar-KW,en' ),
 ('KY', NULL, 'KY', 'Cayman Islands', 'KYD', 'Dollar', null, 'en-KY' ),
 ('KZ', NULL, 'KZ', 'Kazakhstan', 'KZT', 'Tenge', '^(\d{6})$', 'kk,ru' ),
 ('LA', NULL, 'LA', 'Laos', 'LAK', 'Kip', '^(\d{5})$', 'lo,fr,en' ),
 ('LB', NULL, 'LB', 'Lebanon', 'LBP', 'Pound', '^(\d{4}(\d{4})?)$', 'ar-LB,fr-LB,en,hy' ),
 ('LC', NULL, 'LC', 'Saint Lucia', 'XCD', 'Dollar', null, 'en-LC' ),
 ('LI', NULL, 'LI', 'Liechtenstein', 'CHF', 'Franc', '^(\d{4})$', 'de-LI' ),
 ('LK', NULL, 'LK', 'Sri Lanka', 'LKR', 'Rupee', '^(\d{5})$', 'si,ta,en' ),
 ('LR', NULL, 'LR', 'Liberia', 'LRD', 'Dollar', '^(\d{4})$', 'en-LR' ),
 ('LS', NULL, 'LS', 'Lesotho', 'LSL', 'Loti', '^(\d{3})$', 'en-LS,st,zu,xh' ),
 ('LT', NULL, 'LT', 'Lithuania', 'EUR', 'Euro', '^(?:LT)*(\d{5})$', 'lt,ru,pl' ),
 ('LU', NULL, 'LU', 'Luxembourg', 'EUR', 'Euro', '^(?:L-)?\d{4}$', 'lb,de-LU,fr-LU' ),
 ('LV', NULL, 'LV', 'Latvia', 'EUR', 'Euro', '^(?:LV)*(\d{4})$', 'lv,ru,lt' ),
 ('LY', NULL, 'LY', 'Libya', 'LYD', 'Dinar', null, 'ar-LY,it,en' ),
 ('MA', NULL, 'MA', 'Morocco', 'MAD', 'Dirham', '^(\d{5})$', 'ar-MA,ber,fr' ),
 ('MC', NULL, 'MC', 'Monaco', 'EUR', 'Euro', '^(\d{5})$', 'fr-MC,en,it' ),
 ('MD', NULL, 'MD', 'Moldova', 'MDL', 'Leu', '^MD-\d{4}$', 'ro,ru,gag,tr' ),
 ('ME', NULL, 'ME', 'Montenegro', 'EUR', 'Euro', '^(\d{5})$', 'sr,hu,bs,sq,hr,rom' ),
 ('MF', NULL, 'MF', 'Saint Martin', 'EUR', 'Euro', null, 'fr' ),
 ('MG', NULL, 'MG', 'Madagascar', 'MGA', 'Ariary', '^(\d{3})$', 'fr-MG,mg' ),
 ('MH', NULL, 'MH', 'Marshall Islands', 'USD', 'Dollar', '^969\d{2}(-\d{4})$', 'mh,en-MH' ),
 ('MK', NULL, 'MK', 'Macedonia', 'MKD', 'Denar', '^(\d{4})$', 'mk,sq,tr,rmm,sr' ),
 ('ML', NULL, 'ML', 'Mali', 'XOF', 'Franc', null, 'fr-ML,bm' ),
 ('MM', NULL, 'MM', 'Myanmar', 'MMK', 'Kyat', '^(\d{5})$', 'my' ),
 ('MN', NULL, 'MN', 'Mongolia', 'MNT', 'Tugrik', '^(\d{6})$', 'mn,ru' ),
 ('MO', NULL, 'MO', 'Macao', 'MOP', 'Pataca', null, 'zh,zh-MO,pt' ),
 ('MP', NULL, 'MP', 'Northern Mariana Islands', 'USD', 'Dollar', '^9695\d{1}(-\d{4})$', 'fil,tl,zh,ch-MP,en-MP' ),
 ('MQ', NULL, 'MQ', 'Martinique', 'EUR', 'Euro', '^(\d{5})$', 'fr-MQ' ),
 ('MR', NULL, 'MR', 'Mauritania', 'MRO', 'Ouguiya', null, 'ar-MR,fuc,snk,fr,mey,wo' ),
 ('MS', NULL, 'MS', 'Montserrat', 'XCD', 'Dollar', null, 'en-MS' ),
 ('MT', NULL, 'MT', 'Malta', 'EUR', 'Euro', '^[A-Z]{3}\s?\d{4}$', 'mt,en-MT' ),
 ('MU', NULL, 'MU', 'Mauritius', 'MUR', 'Rupee', null, 'en-MU,bho,fr' ),
 ('MV', NULL, 'MV', 'Maldives', 'MVR', 'Rufiyaa', '^(\d{5})$', 'dv,en' ),
 ('MW', NULL, 'MW', 'Malawi', 'MWK', 'Kwacha', null, 'ny,yao,tum,swk' ),
 ('MX', NULL, 'MX', 'Mexico', 'MXN', 'Peso', '^(\d{5})$', 'es-MX' ),
 ('MY', NULL, 'MY', 'Malaysia', 'MYR', 'Ringgit', '^(\d{5})$', 'ms-MY,en,zh,ta,te,ml,pa,th' ),
 ('MZ', NULL, 'MZ', 'Mozambique', 'MZN', 'Metical', '^(\d{4})$', 'pt-MZ,vmw' ),
 ('NA', NULL, 'NA', 'Namibia', 'NAD', 'Dollar', null, 'en-NA,af,de,hz,naq' ),
 ('NC', NULL, 'NC', 'New Caledonia', 'XPF', 'Franc', '^(\d{5})$', 'fr-NC' ),
 ('NE', NULL, 'NE', 'Niger', 'XOF', 'Franc', '^(\d{4})$', 'fr-NE,ha,kr,dje' ),
 ('NF', NULL, 'NF', 'Norfolk Island', 'AUD', 'Dollar', '^(\d{4})$', 'en-NF' ),
 ('NG', NULL, 'NG', 'Nigeria', 'NGN', 'Naira', '^(\d{6})$', 'en-NG,ha,yo,ig,ff' ),
 ('NI', NULL, 'NI', 'Nicaragua', 'NIO', 'Cordoba', '^(\d{7})$', 'es-NI,en' ),
 ('NL', NULL, 'NL', 'Netherlands', 'EUR', 'Euro', '^(\d{4}[A-Z]{2})$', 'nl-NL,fy-NL' ),
 ('NO', NULL, 'NO', 'Norway', 'NOK', 'Krone', '^(\d{4})$', 'no,nb,nn,se,fi' ),
 ('NP', NULL, 'NP', 'Nepal', 'NPR', 'Rupee', '^(\d{5})$', 'ne,en' ),
 ('NR', NULL, 'NR', 'Nauru', 'AUD', 'Dollar', null, 'na,en-NR' ),
 ('NU', NULL, 'NU', 'Niue', 'NZD', 'Dollar', null, 'niu,en-NU' ),
 ('NZ', NULL, 'NZ', 'New Zealand', 'NZD', 'Dollar', '^(\d{4})$', 'en-NZ,mi' ),
 ('OM', NULL, 'OM', 'Oman', 'OMR', 'Rial', '^(\d{3})$', 'ar-OM,en,bal,ur' ),
 ('PA', NULL, 'PA', 'Panama', 'PAB', 'Balboa', null, 'es-PA,en' ),
 ('PE', NULL, 'PE', 'Peru', 'PEN', 'Sol', null, 'es-PE,qu,ay' ),
 ('PE_LIMA', 'PE', 'PE', 'Lima Region', 'PEN', 'Sol', null, 'es-PE,qu,ay' ),
 ('PE_LIMA_LIMA', 'PE_LIMA', 'PE', 'Lima Province', 'PEN', 'Sol', null, 'es-PE,qu,ay' ),
 ('PF', NULL, 'PF', 'French Polynesia', 'XPF', 'Franc', '^((97|98)7\d{2})$', 'fr-PF,ty' ),
 ('PG', NULL, 'PG', 'Papua New Guinea', 'PGK', 'Kina', '^(\d{3})$', 'en-PG,ho,meu,tpi' ),
 ('PH', NULL, 'PH', 'Philippines', 'PHP', 'Peso', '^(\d{4})$', 'tl,en-PH,fil' ),
 ('PK', NULL, 'PK', 'Pakistan', 'PKR', 'Rupee', '^(\d{5})$', 'ur-PK,en-PK,pa,sd,ps,brh' ),
 ('PL', NULL, 'PL', 'Poland', 'PLN', 'Zloty', '^\d{2}-\d{3}$', 'pl' ),
 ('PM', NULL, 'PM', 'Saint Pierre and Miquelon', 'EUR', 'Euro', '^(97500)$', 'fr-PM' ),
 ('PN', NULL, 'PN', 'Pitcairn', 'NZD', 'Dollar', null, 'en-PN' ),
 ('PR', NULL, 'PR', 'Puerto Rico', 'USD', 'Dollar', '^00[679]\d{2}(?:-\d{4})?$', 'en-PR,es-PR' ),
 ('PS', NULL, 'PS', 'Palestinian Territory', 'ILS', 'Shekel', null, 'ar-PS' ),
 ('PT', NULL, 'PT', 'Portugal', 'EUR', 'Euro', '^\d{4}-\d{3}\s?[a-zA-Z]{0,25}$', 'pt-PT,mwl' ),
 ('PW', NULL, 'PW', 'Palau', 'USD', 'Dollar', '^(96940)$', 'pau,sov,en-PW,tox,ja,fil,zh' ),
 ('PY', NULL, 'PY', 'Paraguay', 'PYG', 'Guarani', '^(\d{4})$', 'es-PY,gn' ),
 ('QA', NULL, 'QA', 'Qatar', 'QAR', 'Rial', null, 'ar-QA,es' ),
 ('RE', NULL, 'RE', 'Reunion', 'EUR', 'Euro', '^((97|98)(4|7|8)\d{2})$', 'fr-RE' ),
 ('RO', NULL, 'RO', 'Romania', 'RON', 'Leu', '^(\d{6})$', 'ro,hu,rom' ),
 ('RS', NULL, 'RS', 'Serbia', 'RSD', 'Dinar', '^(\d{6})$', 'sr,hu,bs,rom' ),
 ('RU', NULL, 'RU', 'Russia', 'RUB', 'Ruble', '^(\d{6})$', 'ru,tt,xal,cau,ady,kv,ce,tyv,cv,udm,tut,mns,bua,myv,mdf,chm,ba,inh,tut,kbd,krc,ava,sah,nog' ),
 ('RW', NULL, 'RW', 'Rwanda', 'RWF', 'Franc', null, 'rw,en-RW,fr-RW,sw' ),
 ('SA', NULL, 'SA', 'Saudi Arabia', 'SAR', 'Rial', '^(\d{5})$', 'ar-SA' ),
 ('SB', NULL, 'SB', 'Solomon Islands', 'SBD', 'Dollar', null, 'en-SB,tpi' ),
 ('SC', NULL, 'SC', 'Seychelles', 'SCR', 'Rupee', null, 'en-SC,fr-SC' ),
 ('SD', NULL, 'SD', 'Sudan', 'SDG', 'Pound', '^(\d{5})$', 'ar-SD,en,fia' ),
 ('SS', NULL, 'SS', 'South Sudan', 'SSP', 'Pound', null, 'en' ),
 ('SE', NULL, 'SE', 'Sweden', 'SEK', 'Krona', '^(?:SE)?\d{3}\s\d{2}$', 'sv-SE,se,sma,fi-SE' ),
 ('SG', NULL, 'SG', 'Singapore', 'SGD', 'Dollar', '^(\d{6})$', 'cmn,en-SG,ms-SG,ta-SG,zh-SG' ),
 ('SH', NULL, 'SH', 'Saint Helena', 'SHP', 'Pound', '^(STHL1ZZ)$', 'en-SH' ),
 ('SI', NULL, 'SI', 'Slovenia', 'EUR', 'Euro', '^(?:SI)*(\d{4})$', 'sl,sh' ),
 ('SJ', NULL, 'SJ', 'Svalbard and Jan Mayen', 'NOK', 'Krone', '^(\d{4})$', 'no,ru' ),
 ('SK', NULL, 'SK', 'Slovakia', 'EUR', 'Euro', '^\d{3}\s?\d{2}$', 'sk,hu' ),
 ('SL', NULL, 'SL', 'Sierra Leone', 'SLL', 'Leone', null, 'en-SL,men,tem' ),
 ('SM', NULL, 'SM', 'San Marino', 'EUR', 'Euro', '^(4789\d)$', 'it-SM' ),
 ('SN', NULL, 'SN', 'Senegal', 'XOF', 'Franc', '^(\d{5})$', 'fr-SN,wo,fuc,mnk' ),
 ('SO', NULL, 'SO', 'Somalia', 'SOS', 'Shilling', '^([A-Z]{2}\d{5})$', 'so-SO,ar-SO,it,en-SO' ),
 ('SR', NULL, 'SR', 'Suriname', 'SRD', 'Dollar', null, 'nl-SR,en,srn,hns,jv' ),
 ('ST', NULL, 'ST', 'Sao Tome and Principe', 'STD', 'Dobra', null, 'pt-ST' ),
 ('SV', NULL, 'SV', 'El Salvador', 'USD', 'Dollar', '^(?:CP)*(\d{4})$', 'es-SV' ),
 ('SX', NULL, 'SX', 'Sint Maarten', 'ANG', 'Guilder', null, 'nl,en' ),
 ('SY', NULL, 'SY', 'Syria', 'SYP', 'Pound', null, 'ar-SY,ku,hy,arc,fr,en' ),
 ('SZ', NULL, 'SZ', 'Swaziland', 'SZL', 'Lilangeni', '^([A-Z]\d{3})$', 'en-SZ,ss-SZ' ),
 ('TC', NULL, 'TC', 'Turks and Caicos Islands', 'USD', 'Dollar', '^(TKCA 1ZZ)$', 'en-TC' ),
 ('TD', NULL, 'TD', 'Chad', 'XAF', 'Franc', null, 'fr-TD,ar-TD,sre' ),
 ('TF', NULL, 'TF', 'French Southern Territories', 'EUR', 'Euro  ', null, 'fr' ),
 ('TG', NULL, 'TG', 'Togo', 'XOF', 'Franc', null, 'fr-TG,ee,hna,kbp,dag,ha' ),
 ('TH', NULL, 'TH', 'Thailand', 'THB', 'Baht', '^(\d{5})$', 'th,en' ),
 ('TJ', NULL, 'TJ', 'Tajikistan', 'TJS', 'Somoni', '^(\d{6})$', 'tg,ru' ),
 ('TK', NULL, 'TK', 'Tokelau', 'NZD', 'Dollar', null, 'tkl,en-TK' ),
 ('TL', NULL, 'TL', 'East Timor', 'USD', 'Dollar', null, 'tet,pt-TL,id,en' ),
 ('TM', NULL, 'TM', 'Turkmenistan', 'TMT', 'Manat', '^(\d{6})$', 'tk,ru,uz' ),
 ('TN', NULL, 'TN', 'Tunisia', 'TND', 'Dinar', '^(\d{4})$', 'ar-TN,fr' ),
 ('TO', NULL, 'TO', 'Tonga', 'TOP', 'Pa''anga', null, 'to,en-TO' ),
 ('TR', NULL, 'TR', 'Turkey', 'TRY', 'Lira', '^(\d{5})$', 'tr-TR,ku,diq,az,av' ),
 ('TT', NULL, 'TT', 'Trinidad and Tobago', 'TTD', 'Dollar', null, 'en-TT,hns,fr,es,zh' ),
 ('TV', NULL, 'TV', 'Tuvalu', 'AUD', 'Dollar', null, 'tvl,en,sm,gil' ),
 ('TW', NULL, 'TW', 'Taiwan', 'TWD', 'Dollar', '^(\d{5})$', 'zh-TW,zh,nan,hak' ),
 ('TZ', NULL, 'TZ', 'Tanzania', 'TZS', 'Shilling', null, 'sw-TZ,en,ar' ),
 ('UA', NULL, 'UA', 'Ukraine', 'UAH', 'Hryvnia', '^(\d{5})$', 'uk,ru-UA,rom,pl,hu' ),
 ('UG', NULL, 'UG', 'Uganda', 'UGX', 'Shilling', null, 'en-UG,lg,sw,ar' ),
 ('UM', NULL, 'UM', 'United States Minor Outlying Islands', 'USD', 'Dollar ', null, 'en-UM' ),
 ('US', NULL, 'US', 'United States', 'USD', 'Dollar', '^\d{5}(-\d{4})?$', 'en-US,es-US,haw,fr' ),
 ('US_CA', 'US', 'US', 'California, US', 'USD', 'Dollar', '^\d{5}(-\d{4})?$', 'en-US,es-US,haw,fr' ),
 ('US_CA_SF', 'US', 'US', 'San Francisco, CA', 'USD', 'Dollar', '^\d{5}(-\d{4})?$', 'en-US,es-US,haw,fr' ),
 ('UY', NULL, 'UY', 'Uruguay', 'UYU', 'Peso', '^(\d{5})$', 'es-UY' ),
 ('UZ', NULL, 'UZ', 'Uzbekistan', 'UZS', 'Som', '^(\d{6})$', 'uz,ru,tg' ),
 ('VA', NULL, 'VA', 'Vatican', 'EUR', 'Euro', '^(\d{5})$', 'la,it,fr' ),
 ('VC', NULL, 'VC', 'Saint Vincent and the Grenadines', 'XCD', 'Dollar', null, 'en-VC,fr' ),
 ('VE', NULL, 'VE', 'Venezuela', 'VEF', 'Bolivar', '^(\d{4})$', 'es-VE' ),
 ('VG', NULL, 'VG', 'British Virgin Islands', 'USD', 'Dollar', null, 'en-VG' ),
 ('VI', NULL, 'VI', 'U.S. Virgin Islands', 'USD', 'Dollar', '^008\d{2}(?:-\d{4})?$', 'en-VI' ),
 ('VN', NULL, 'VN', 'Vietnam', 'VND', 'Dong', '^(\d{6})$', 'vi,en,fr,zh,km' ),
 ('VU', NULL, 'VU', 'Vanuatu', 'VUV', 'Vatu', null, 'bi,en-VU,fr-VU' ),
 ('WF', NULL, 'WF', 'Wallis and Futuna', 'XPF', 'Franc', '^(986\d{2})$', 'wls,fud,fr-WF' ),
 ('WS', NULL, 'WS', 'Samoa', 'WST', 'Tala', null, 'sm,en-WS' ),
 ('YE', NULL, 'YE', 'Yemen', 'YER', 'Rial', null, 'ar-YE' ),
 ('YT', NULL, 'YT', 'Mayotte', 'EUR', 'Euro', '^(\d{5})$', 'fr-YT' ),
 ('ZA', NULL, 'ZA', 'South Africa', 'ZAR', 'Rand', '^(\d{4})$', 'zu,xh,af,nso,en-ZA,tn,st,ts,ss,ve,nr' ),
 ('ZM', NULL, 'ZM', 'Zambia', 'ZMW', 'Kwacha', '^(\d{5})$', 'en-ZM,bem,loz,lun,lue,ny,toi' ),
 ('ZW', NULL, 'ZW', 'Zimbabwe', 'ZWL', 'Dollar', null, 'en-ZW,sn,nr,nd' ),
 ('CS', NULL, 'CS', 'Serbia and Montenegro', 'RSD', 'Dinar', '^(\d{5})$', 'cu,hu,sq,sr' ),
 ('AN', NULL, 'AN', 'Netherlands Antilles', 'ANG', 'Guilder', null, 'nl-AN,en,es', 8505032, 'GP');
